<a href="https://colab.research.google.com/github/masolopa/MINERIADEDATOS/blob/main/EV1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

#El contexto del data set es sobre las estimaciones de taza de pobreza multidimensional por comuna en Chile del año 2015
#Integrantes: Alejandra Guzman - Macarena Lobos Sección 002D
#https://github.com/masolopa/MINERIADEDATOS

In [2]:
#Se importa el data set del año 2015
df = pd.read_excel("/content/planilla_estimaciones_pobreza_2015.xlsx")

In [3]:
#Se observa el data frame en bruto
df

,"Estimaciones de Tasa de Pobreza Multidimensional por Comuna, considerando Entorno y Redes y Aplicación de Metodologías de: Estimación directa, Estimación para Áreas Pequeñas (SAE) e Imputación de Medias por Conglomerados (IMC), 2015",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Código,Región,Nombre comuna,Número de personas en situación de pobreza por...,Porcentaje de personas en situación de pobreza...,Límite inferior,Límite superior,Metodología de Estimación
2,1101,I de Tarapacá,Iquique,9491,0.053294,0.034605,0.081227,Estimación Directa
3,1107,I de Tarapacá,Alto Hospicio,9768,0.085072,0.064137,0.112023,Estimación Directa
4,1401,I de Tarapacá,Pozo Almonte,1515,0.103265,0.072762,0.144562,Estimación Directa
...,...,...,...,...,...,...,...,...
342,14204,XIV de los Ríos,Rio Bueno,5113,0.171232,0.107617,0.261436,Estimación Directa
343,15101,XV de Arica y Parinacota,Arica,14573,0.088609,0.068152,0.114452,Estimación Directa
344,15102,XV de Arica y Parinacota,Camarones,217.5172,0.146674,0.07265,0.241199,SAE
345,15201,XV de Arica y Parinacota,Putre,240,0.311284,0.2193,0.421043,Estimación Directa
346,15202,XV de Arica y Parinacota,General Lagos,267.9631,0.277395,NaN,NaN,IMC

In [4]:
#Se eliminan las primeras dos filas del data frame seleccionando el número de posición de cada fila a la vez
df = df.drop(index= [0, 1])

In [5]:
#Se observa el data frame con las dos filas de posición 0 y 1 eliminadas
df

,"Estimaciones de Tasa de Pobreza Multidimensional por Comuna, considerando Entorno y Redes y Aplicación de Metodologías de: Estimación directa, Estimación para Áreas Pequeñas (SAE) e Imputación de Medias por Conglomerados (IMC), 2015",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,1101,I de Tarapacá,Iquique,9491,0.053294,0.034605,0.081227,Estimación Directa
3,1107,I de Tarapacá,Alto Hospicio,9768,0.085072,0.064137,0.112023,Estimación Directa
4,1401,I de Tarapacá,Pozo Almonte,1515,0.103265,0.072762,0.144562,Estimación Directa
5,1402,I de Tarapacá,Camiña,300.2006,0.348665,0.276406,0.453704,SAE
6,1403,I de Tarapacá,Colchane,328.2058,0.239566,NaN,NaN,IMC
...,...,...,...,...,...,...,...,...
342,14204,XIV de los Ríos,Rio Bueno,5113,0.171232,0.107617,0.261436,Estimación Directa
343,15101,XV de Arica y Parinacota,Arica,14573,0.088609,0.068152,0.114452,Estimación Directa
344,15102,XV de Arica y Parinacota,Camarones,217.5172,0.146674,0.07265,0.241199,SAE
345,15201,XV de Arica y Parinacota,Putre,240,0.311284,0.2193,0.421043,Estimación Directa
346,15202,XV de Arica y Parinacota,General Lagos,267.9631,0.277395,NaN,NaN,IMC

In [6]:
#Se consultan los nombres de las columnas del data frame
print("Nombres de columnas actuales:")
print(df.columns.tolist())

Nombres de columnas actuales:
['Estimaciones de Tasa de Pobreza Multidimensional por Comuna, considerando Entorno y Redes y Aplicación de Metodologías de: Estimación directa, Estimación para Áreas Pequeñas (SAE) e Imputación de Medias por Conglomerados (IMC), 2015', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']

In [7]:
#Se renombran las columnas
df.columns = ['Código comuna', 'Región','Nombre comuna', 'Número de personas en situación de pobreza por ingresos','Porcentaje de personas en situación de pobreza por ingresos', 'Límite inferior','Límite superior', 'Metodología de Estimación']
display(df.head())

,Código comuna,Región,Nombre comuna,Número de personas en situación de pobreza por ingresos,Porcentaje de personas en situación de pobreza por ingresos,Límite inferior,Límite superior,Metodología de Estimación
2,1101,I de Tarapacá,Iquique,9491,0.053294,0.034605,0.081227,Estimación Directa
3,1107,I de Tarapacá,Alto Hospicio,9768,0.085072,0.064137,0.112023,Estimación Directa
4,1401,I de Tarapacá,Pozo Almonte,1515,0.103265,0.072762,0.144562,Estimación Directa
5,1402,I de Tarapacá,Camiña,300.2006,0.348665,0.276406,0.453704,SAE
6,1403,I de Tarapacá,Colchane,328.2058,0.239566,NaN,NaN,IMC

In [8]:
#df.to_csv("modificado.csv") Se hace una conversión del data frame a versión csv, ya que la base de origen es tipo excel

In [9]:
#Se muestran las primeras 5 filas
df.head()

,Código comuna,Región,Nombre comuna,Número de personas en situación de pobreza por ingresos,Porcentaje de personas en situación de pobreza por ingresos,Límite inferior,Límite superior,Metodología de Estimación
2,1101,I de Tarapacá,Iquique,9491,0.053294,0.034605,0.081227,Estimación Directa
3,1107,I de Tarapacá,Alto Hospicio,9768,0.085072,0.064137,0.112023,Estimación Directa
4,1401,I de Tarapacá,Pozo Almonte,1515,0.103265,0.072762,0.144562,Estimación Directa
5,1402,I de Tarapacá,Camiña,300.2006,0.348665,0.276406,0.453704,SAE
6,1403,I de Tarapacá,Colchane,328.2058,0.239566,NaN,NaN,IMC

In [10]:
#Se muestran las últimas 5 filas del data frame
df.tail()

,Código comuna,Región,Nombre comuna,Número de personas en situación de pobreza por ingresos,Porcentaje de personas en situación de pobreza por ingresos,Límite inferior,Límite superior,Metodología de Estimación
342,14204,XIV de los Ríos,Rio Bueno,5113,0.171232,0.107617,0.261436,Estimación Directa
343,15101,XV de Arica y Parinacota,Arica,14573,0.088609,0.068152,0.114452,Estimación Directa
344,15102,XV de Arica y Parinacota,Camarones,217.5172,0.146674,0.07265,0.241199,SAE
345,15201,XV de Arica y Parinacota,Putre,240,0.311284,0.2193,0.421043,Estimación Directa
346,15202,XV de Arica y Parinacota,General Lagos,267.9631,0.277395,NaN,NaN,IMC

In [11]:
#Se listan las columnas del data frame
df.columns

Index(['Código comuna', 'Región', 'Nombre comuna',
       'Número de personas en situación de pobreza por ingresos',
       'Porcentaje de personas en situación de pobreza por ingresos',
       'Límite inferior', 'Límite superior', 'Metodología de Estimación'],
      dtype='object')

In [12]:
#Se revisan los valores nulos de cada columna del data frame
df.isna().sum()

Código comuna                                                   0
Región                                                          0
Nombre comuna                                                   0
Número de personas en situación de pobreza por ingresos         0
Porcentaje de personas en situación de pobreza por ingresos     0
Límite inferior                                                21
Límite superior                                                21
Metodología de Estimación                                       0
dtype: int64

In [13]:
#Se importa el data set del año 2024
df2 = pd.read_excel("/content/sae_multidimensional_2024.xlsx")

In [14]:
df2

,Estimaciones de Índice de Pobreza Multidimensional por comuna. Aplicación de Metodologías de Estimación para Áreas Pequeñas (SAE) 2024,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Código,Región,Nombre comuna,Número de personas según proyecciones de pobla...,Número de personas en situación de pobreza mul...,Porcentaje de personas en situacion de pobreza...,Límite inferior,Límite superior,Presencia de la comuna en la muestra Casen,Tipo de estimación SAE (***)
2,1101,Tarapacá,Iquique,232455,43108.781225,0.18545,0.163506,0.207394,Sí,Directa y Sintética (Fay-Herriot)
3,1107,Tarapacá,Alto Hospicio,144554,40866.517698,0.282708,0.255357,0.310058,Sí,Directa y Sintética (Fay-Herriot)
4,1401,Tarapacá,Pozo Almonte,18811,3646.420183,0.193845,0.142099,0.245592,Sí,Directa y Sintética (Fay-Herriot)
...,...,...,...,...,...,...,...,...,...,...
348,La metodología de áreas pequeñas busca realiza...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,Las estimaciones presentadas se basan en la nu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,(*) Proyecciones de población comunal en vivie...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,(**) Este número se obtiene de multiplicar las...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,(***) Las estimaciones para área pequeña asign...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
#Se eliminan las primeras dos filas del data frame 2 seleccionando el número de posición de cada fila a la vez
df2 = df2.drop(index= [0, 1])

In [16]:
#Se renombran las columnas
df2.columns = ['Código comuna', 'Región','Nombre comuna', 'Número de personas según proyecciones de población (*)','Número de personas en situación de pobreza multidimensional (**)', 'Porcentaje de personas en situacion de pobreza multidimensional 2024','Límite inferior', 'Límite superior', 'Presencia de la comuna en la muestra Casen', 'Tipo de estimación SAE (***)']
display(df.head())

,Código comuna,Región,Nombre comuna,Número de personas en situación de pobreza por ingresos,Porcentaje de personas en situación de pobreza por ingresos,Límite inferior,Límite superior,Metodología de Estimación
2,1101,I de Tarapacá,Iquique,9491,0.053294,0.034605,0.081227,Estimación Directa
3,1107,I de Tarapacá,Alto Hospicio,9768,0.085072,0.064137,0.112023,Estimación Directa
4,1401,I de Tarapacá,Pozo Almonte,1515,0.103265,0.072762,0.144562,Estimación Directa
5,1402,I de Tarapacá,Camiña,300.2006,0.348665,0.276406,0.453704,SAE
6,1403,I de Tarapacá,Colchane,328.2058,0.239566,NaN,NaN,IMC

In [17]:
#Se muestran las últimas 5 filas del data frame 2
df2.tail()

,Código comuna,Región,Nombre comuna,Número de personas según proyecciones de población (*),Número de personas en situación de pobreza multidimensional (**),Porcentaje de personas en situacion de pobreza multidimensional 2024,Límite inferior,Límite superior,Presencia de la comuna en la muestra Casen,Tipo de estimación SAE (***)
348,La metodología de áreas pequeñas busca realiza...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,Las estimaciones presentadas se basan en la nu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,(*) Proyecciones de población comunal en vivie...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,(**) Este número se obtiene de multiplicar las...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,(***) Las estimaciones para área pequeña asign...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df.info() #Muestra en detalle cuantas columnas hay, sus nombres, también muestra que hay 345 filas de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345 entries, 2 to 346
Data columns (total 8 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Código comuna                                                345 non-null    object
 1   Región                                                       345 non-null    object
 2   Nombre comuna                                                345 non-null    object
 3   Número de personas en situación de pobreza por ingresos      345 non-null    object
 4   Porcentaje de personas en situación de pobreza por ingresos  345 non-null    object
 5   Límite inferior                                              324 non-null    object
 6   Límite superior                                              324 non-null    object
 7   Metodología de Estimación                                    345 non-null    object
dtypes: object(8)
memory usage: 21.7+ KB

In [19]:
#df2.to_csv("modificado2.csv")

In [20]:
df2.info()#Muestra en detalle cuantas columnas hay, sus nombres, también muestra que hay 350 filas de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 2 to 352
Data columns (total 10 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   Código comuna                                                         350 non-null    object
 1   Región                                                                345 non-null    object
 2   Nombre comuna                                                         345 non-null    object
 3   Número de personas según proyecciones de población (*)                345 non-null    object
 4   Número de personas en situación de pobreza multidimensional (**)      345 non-null    object
 5   Porcentaje de personas en situacion de pobreza multidimensional 2024  345 non-null    object
 6   Límite inferior                                                       345 non-null    object
 7   Límite superior                                                       345 non-null    object
 8   Presencia de la comuna en la muestra Casen                            345 non-null    object
 9   Tipo de estimación SAE (***)                                          345 non-null    object
dtypes: object(10)
memory usage: 27.6+ KB

In [21]:
df.shape #Muestra filas y luego columnas totales

(345, 8)

In [22]:
df2.shape #Muestra filas y luego columnas totales

(351, 10)

In [23]:
df2.isna().sum() #Muestra que dentro del df2 hay 6 nulos en cada columna a excepción de la columna Código comuna que tiene un dato nulo

Código comuna                                                           1
Región                                                                  6
Nombre comuna                                                           6
Número de personas según proyecciones de población (*)                  6
Número de personas en situación de pobreza multidimensional (**)        6
Porcentaje de personas en situacion de pobreza multidimensional 2024    6
Límite inferior                                                         6
Límite superior                                                         6
Presencia de la comuna en la muestra Casen                              6
Tipo de estimación SAE (***)                                            6
dtype: int64

In [24]:
df.describe() #Estadistica descriptiva sobre variables numericas, se muestra que en la comuna General lagos de la región del Biobio se encuentra mayor cantidad de muestras al año 2015

,Código comuna,Región,Nombre comuna,Número de personas en situación de pobreza por ingresos,Porcentaje de personas en situación de pobreza por ingresos,Límite inferior,Límite superior,Metodología de Estimación
count,345,345,345,345,345.000000,324.0000,324.000000,345
unique,345,15,345,344,343.000000,324.0000,324.000000,3
top,15202,VIII del Biobío,General Lagos,4632,0.171126,0.2193,0.421043,SAE
freq,1,54,1,2,2.000000,1.0000,1.000000,185

In [25]:
df2.describe() #Estadistica descriptiva sobre variables numericas, se puede interpretar que en la comuna de San Nicolás de la Región Metropolitana es en donde hubieron más muestras al año 2024

,Código comuna,Región,Nombre comuna,Número de personas según proyecciones de población (*),Número de personas en situación de pobreza multidimensional (**),Porcentaje de personas en situacion de pobreza multidimensional 2024,Límite inferior,Límite superior,Presencia de la comuna en la muestra Casen,Tipo de estimación SAE (***)
count,350,345,345,345,345.000000,345.000000,345,345.000000,345,345
unique,350,16,345,342,345.000000,345.000000,340,345.000000,2,2
top,(***) Las estimaciones para área pequeña asign...,Metropolitana,San Nicolás,19779,1855.039212,0.148119,0,0.189405,Sí,Directa y Sintética (Fay-Herriot)
freq,1,52,1,2,1.000000,1.000000,6,1.000000,335,294

In [26]:
#Agrupación de las columnas por tipos de datos

tipos= df.columns.to_series().groupby(df.dtypes).groups

#Conociendo la lista de columnas categoricas

ctext =tipos[np.dtype('object')]
len(ctext) #Cantidad de columnas con datos categóricos

8

In [27]:
#Agrupación de las columnas por tipos de datos

tipos= df2.columns.to_series().groupby(df.dtypes).groups

#Conociendo la lista de columnas categoricas

ctext =tipos[np.dtype('object')]
len(ctext) #Cantidad de columnas con datos categóricos

5

In [28]:
#Conociendo la lista de columnas numéricas

columnas = df.columns
cnum = list(set(columnas) - set(ctext))
len(cnum)

3

In [29]:
#Conociendo la lista de columnas numéricas

columnas = df2.columns
cnum = list(set(columnas) - set(ctext))
len(cnum)

5

In [36]:
#Se comprueban los nulos del df
df.isnull().any().any()

np.True_

In [35]:
#Se comprueban los nulos del df2
df2.isnull().any().any()

np.True_

In [32]:
#Completando valores faltantes categóricos de df2
for columna in ctext:
  mode = df2[columna].mode()[0]
  df2[columna] = df2[columna].fillna(mode)

/tmp/ipykernel_33448/4016361816.py:3: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  mode = df2[columna].mode()[0]
/tmp/ipykernel_33448/4016361816.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2[columna] = df2[columna].fillna(mode)

In [37]:
#Completando valores faltantes categóricos de df
for columna in ctext:
  mode = df[columna].mode()[0]
  df[columna] = df[columna].fillna(mode)

/tmp/ipykernel_33448/2422918103.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[columna] = df[columna].fillna(mode)

In [38]:
#Se vuelve a comprobar los nulos
df2.isnull().any().any()

np.True_

In [42]:
df.isnull().any().any() #Se vuelve a comprobar los nulos

np.False_

In [41]:
ascn_order= np.sort(df["Código comuna"].unique())  #Aquí ordena los códigos de las comunas en orden ascendente
print(ascn_order)

[ 1101  1107  1401  1402  1403  1404  1405  2101  2102  2103  2104  2201
  2202  2203  2301  2302  3101  3102  3103  3201  3202  3301  3302  3303
  3304  4101  4102  4103  4104  4105  4106  4201  4202  4203  4204  4301
  4302  4303  4304  4305  5101  5102  5103  5104  5105  5107  5109  5201
  5301  5302  5303  5304  5401  5402  5403  5404  5405  5501  5502  5503
  5504  5506  5601  5602  5603  5604  5605  5606  5701  5702  5703  5704
  5705  5706  5801  5802  5803  5804  6101  6102  6103  6104  6105  6106
  6107  6108  6109  6110  6111  6112  6113  6114  6115  6116  6117  6201
  6202  6203  6204  6205  6206  6301  6302  6303  6304  6305  6306  6307
  6308  6309  6310  7101  7102  7103  7104  7105  7106  7107  7108  7109
  7110  7201  7202  7203  7301  7302  7303  7304  7305  7306  7307  7308
  7309  7401  7402  7403  7404  7405  7406  7407  7408  8101  8102  8103
  8104  8105  8106  8107  8108  8109  8110  8111  8112  8201  8202  8203
  8204  8205  8206  8207  8301  8302  8303  8304  8305  8306  8307  8308
  8309  8310  8311  8312  8313  8314  8401  8402  8403  8404  8405  8406
  8407  8408  8409  8410  8411  8412  8413  8414  8415  8416  8417  8418
  8419  8420  8421  9101  9102  9103  9104  9105  9106  9107  9108  9109
  9110  9111  9112  9113  9114  9115  9116  9117  9118  9119  9120  9121
  9201  9202  9203  9204  9205  9206  9207  9208  9209  9210  9211 10101
 10102 10103 10104 10105 10106 10107 10108 10109 10201 10202 10203 10204
 10205 10206 10207 10208 10209 10210 10301 10302 10303 10304 10305 10306
 10307 10401 10402 10403 10404 11101 11102 11201 11202 11203 11301 11302
 11303 11401 11402 12101 12102 12103 12104 12201 12301 12302 12303 12401
 12402 13101 13102 13103 13104 13105 13106 13107 13108 13109 13110 13111
 13112 13113 13114 13115 13116 13117 13118 13119 13120 13121 13122 13123
 13124 13125 13126 13127 13128 13129 13130 13131 13132 13201 13202 13203
 13301 13302 13303 13401 13402 13403 13404 13501 13502 13503 13504 13505
 13601 13602 13603 13604 13605 14101 14102 14103 14104 14105 14106 14107
 14108 14201 14202 14203 14204 15101 15102 15201 15202]

In [43]:
df['Región'].value_counts() #Aquí me muestra las cantidades de personas por región

Región
VIII del Biobío                                  54
XIII Metropolitana de Santiago                   52
V de Valparaíso                                  38
VI del Libertador General Bernardo O'Higgins     33
IX de la Araucanía                               32
X de los Lagos                                   30
VII del Maule                                    30
IV de Coquimbo                                   15
XIV de los Ríos                                  12
XII de Magallanes y Antártica Chilena            10
XI Aysén del General Carlos Ibáñez del Campo     10
II de Antofagasta                                 9
III de Atacama                                    9
I de Tarapacá                                     7
XV de Arica y Parinacota                          4
Name: count, dtype: int64

In [45]:
df2['Región'].value_counts() #Aquí me muestra las cantidades de personas por región

Región
Metropolitana         58
Valparaíso            38
Biobío                33
 O'Higgins            33
La Araucanía          32
Los Lagos             30
Maule                 30
Ñuble                 21
Coquimbo              15
Los Ríos              12
Magallanes            10
Aysén                 10
Antofagasta            9
Atacama                9
Tarapacá               7
Arica y Parinacota     4
Name: count, dtype: int64

In [ ]:
# Gráfico de tortas del porcentaje de donantes
# Agrupando por DONOR_FLAG
donantes = df.groupby('DONOR_FLAG').IDX.count()
# Creando las leyendas del grafico.
labels = [ 'Donante\n' + str(round(x * 1.0 / donantes.sum() *
100.0, 2)) + '%' for x in donantes ]
labels[0] = 'No ' + labels[0]
plt.pie(donantes, labels=labels)
plt.title('Porcion de donantes')
plt.show()