<a href="https://colab.research.google.com/github/masolopa/MINERIADEDATOS/blob/main/PRACTICA_CSV1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [7]:
#Cargar el data set
df = pd.read_csv("mxmh_survey_results.csv")

In [9]:
df.head()

,Timestamp,Age,Primary streaming service,Hours per day,While working,Instrumentalist,Composer,Fav genre,Exploratory,Foreign languages,...,Frequency [R&B],Frequency [Rap],Frequency [Rock],Frequency [Video game music],Anxiety,Depression,Insomnia,OCD,Music effects,Permissions
0,8/27/2022 19:29:02,18.0,Spotify,3.0,Yes,Yes,Yes,Latin,Yes,Yes,...,Sometimes,Very frequently,Never,Sometimes,3.0,0.0,1.0,0.0,NaN,I understand.
1,8/27/2022 19:57:31,63.0,Pandora,1.5,Yes,No,No,Rock,Yes,No,...,Sometimes,Rarely,Very frequently,Rarely,7.0,2.0,2.0,1.0,NaN,I understand.
2,8/27/2022 21:28:18,18.0,Spotify,4.0,No,No,No,Video game music,No,Yes,...,Never,Rarely,Rarely,Very frequently,7.0,7.0,10.0,2.0,No effect,I understand.
3,8/27/2022 21:40:40,61.0,YouTube Music,2.5,Yes,No,Yes,Jazz,Yes,Yes,...,Sometimes,Never,Never,Never,9.0,7.0,3.0,3.0,Improve,I understand.
4,8/27/2022 21:54:47,18.0,Spotify,4.0,Yes,No,No,R&B,Yes,No,...,Very frequently,Very frequently,Never,Rarely,7.0,2.0,5.0,9.0,Improve,I understand.

In [11]:
df.tail()

,Timestamp,Age,Primary streaming service,Hours per day,While working,Instrumentalist,Composer,Fav genre,Exploratory,Foreign languages,...,Frequency [R&B],Frequency [Rap],Frequency [Rock],Frequency [Video game music],Anxiety,Depression,Insomnia,OCD,Music effects,Permissions
731,10/30/2022 14:37:28,17.0,Spotify,2.0,Yes,Yes,No,Rock,Yes,Yes,...,Never,Rarely,Very frequently,Never,7.0,6.0,0.0,9.0,Improve,I understand.
732,11/1/2022 22:26:42,18.0,Spotify,1.0,Yes,Yes,No,Pop,Yes,Yes,...,Never,Never,Sometimes,Sometimes,3.0,2.0,2.0,5.0,Improve,I understand.
733,11/3/2022 23:24:38,19.0,Other streaming service,6.0,Yes,No,Yes,Rap,Yes,No,...,Sometimes,Sometimes,Rarely,Rarely,2.0,2.0,2.0,2.0,Improve,I understand.
734,11/4/2022 17:31:47,19.0,Spotify,5.0,Yes,Yes,No,Classical,No,No,...,Never,Never,Never,Sometimes,2.0,3.0,2.0,1.0,Improve,I understand.
735,11/9/2022 1:55:20,29.0,YouTube Music,2.0,Yes,No,No,Hip hop,Yes,Yes,...,Very frequently,Very frequently,Very frequently,Rarely,2.0,2.0,2.0,5.0,Improve,I understand.

In [13]:
df.columns #saber la cantidad de columnas

Index(['Timestamp', 'Age', 'Primary streaming service', 'Hours per day',
       'While working', 'Instrumentalist', 'Composer', 'Fav genre',
       'Exploratory', 'Foreign languages', 'BPM', 'Frequency [Classical]',
       'Frequency [Country]', 'Frequency [EDM]', 'Frequency [Folk]',
       'Frequency [Gospel]', 'Frequency [Hip hop]', 'Frequency [Jazz]',
       'Frequency [K pop]', 'Frequency [Latin]', 'Frequency [Lofi]',
       'Frequency [Metal]', 'Frequency [Pop]', 'Frequency [R&B]',
       'Frequency [Rap]', 'Frequency [Rock]', 'Frequency [Video game music]',
       'Anxiety', 'Depression', 'Insomnia', 'OCD', 'Music effects',
       'Permissions'],
      dtype='object')

In [28]:
cant_cat_edad = df["Age"].value_counts()
print(cant_cat_edad)

Age
18.0    85
19.0    61
17.0    59
21.0    52
16.0    44
        ..
80.0     1
50.0     1
68.0     1
46.0     1
89.0     1
Name: count, Length: 61, dtype: int64

In [43]:
ascn_order= np.sort(df["Age"].unique())  #Aquí ordena las edades de las personas que hicieron las encuestas en orden ascendente
print(ascn_order)

[10. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28.
 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 46. 48.
 49. 50. 51. 53. 54. 55. 56. 57. 58. 59. 60. 61. 63. 64. 65. 67. 68. 69.
 70. 71. 72. 73. 74. 80. 89. nan]

In [41]:
df["Age"].unique() #Aquí ordena las edades de las personas que hicieron las encuestas

array([18., 63., 61., 21., 19., nan, 17., 16., 15., 14., 20., 26., 23.,
       37., 36., 24., 22., 42., 25., 32., 29., 41., 31., 33., 30., 43.,
       28., 34., 13., 35., 27., 53., 49., 60., 38., 44., 40., 64., 56.,
       59., 10., 12., 54., 57., 69., 72., 73., 39., 58., 67., 70., 55.,
       48., 71., 74., 51., 65., 80., 50., 68., 46., 89.])

In [45]:
df['Age'].value_counts() #Aquí me muestra las cantidades de personas que hay por edad

Age
18.0    85
19.0    61
17.0    59
21.0    52
16.0    44
        ..
80.0     1
50.0     1
68.0     1
46.0     1
89.0     1
Name: count, Length: 61, dtype: int64

In [42]:
df["Composer"].value_counts() #En este apartado cuenta cuantas personas en la encuesta son compositoras donde 609 si lo son y 126 no lo son

Composer
No     609
Yes    126
Name: count, dtype: int64

In [47]:
df.isnull().sum() #Me muestra los nulos

Timestamp                         0
Age                               1
Primary streaming service         1
Hours per day                     0
While working                     3
Instrumentalist                   4
Composer                          1
Fav genre                         0
Exploratory                       0
Foreign languages                 4
BPM                             107
Frequency [Classical]             0
Frequency [Country]               0
Frequency [EDM]                   0
Frequency [Folk]                  0
Frequency [Gospel]                0
Frequency [Hip hop]               0
Frequency [Jazz]                  0
Frequency [K pop]                 0
Frequency [Latin]                 0
Frequency [Lofi]                  0
Frequency [Metal]                 0
Frequency [Pop]                   0
Frequency [R&B]                   0
Frequency [Rap]                   0
Frequency [Rock]                  0
Frequency [Video game music]      0
Anxiety                           0
Depression                        0
Insomnia                          0
OCD                               0
Music effects                     8
Permissions                       0
dtype: int64

In [49]:
df_limpio = df.dropna() #Crea una database limpia sin nulos

In [55]:
df_limpio.isnull().sum() #Cuenta y muestra los nulos de la database limpia

Timestamp                       0
Age                             0
Primary streaming service       0
Hours per day                   0
While working                   0
Instrumentalist                 0
Composer                        0
Fav genre                       0
Exploratory                     0
Foreign languages               0
BPM                             0
Frequency [Classical]           0
Frequency [Country]             0
Frequency [EDM]                 0
Frequency [Folk]                0
Frequency [Gospel]              0
Frequency [Hip hop]             0
Frequency [Jazz]                0
Frequency [K pop]               0
Frequency [Latin]               0
Frequency [Lofi]                0
Frequency [Metal]               0
Frequency [Pop]                 0
Frequency [R&B]                 0
Frequency [Rap]                 0
Frequency [Rock]                0
Frequency [Video game music]    0
Anxiety                         0
Depression                      0
Insomnia                        0
OCD                             0
Music effects                   0
Permissions                     0
dtype: int64

In [58]:
df_limpio.to_csv("Database_limpia_musica.csv")

In [64]:
df_limpio.info()  #Da la información de cada una de las columnas de la data, se puede notar que hay 616 personas encuestadas, que no hay datos nulos, que hay 2 tipos de data solamente

<class 'pandas.core.frame.DataFrame'>
Index: 616 entries, 2 to 735
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Timestamp                     616 non-null    object
 1   Age                           616 non-null    float64
 2   Primary streaming service     616 non-null    object
 3   Hours per day                 616 non-null    float64
 4   While working                 616 non-null    object
 5   Instrumentalist               616 non-null    object
 6   Composer                      616 non-null    object
 7   Fav genre                     616 non-null    object
 8   Exploratory                   616 non-null    object
 9   Foreign languages             616 non-null    object
 10  BPM                           616 non-null    float64
 11  Frequency [Classical]         616 non-null    object
 12  Frequency [Country]           616 non-null    object
 13  Frequency [EDM]               616 non-null    object
 14  Frequency [Folk]              616 non-null    object
 15  Frequency [Gospel]            616 non-null    object
 16  Frequency [Hip hop]           616 non-null    object
 17  Frequency [Jazz]              616 non-null    object
 18  Frequency [K pop]             616 non-null    object
 19  Frequency [Latin]             616 non-null    object
 20  Frequency [Lofi]              616 non-null    object
 21  Frequency [Metal]             616 non-null    object
 22  Frequency [Pop]               616 non-null    object
 23  Frequency [R&B]               616 non-null    object
 24  Frequency [Rap]               616 non-null    object
 25  Frequency [Rock]              616 non-null    object
 26  Frequency [Video game music]  616 non-null    object
 27  Anxiety                       616 non-null    float64
 28  Depression                    616 non-null    float64
 29  Insomnia                      616 non-null    float64
 30  OCD                           616 non-null    float64
 31  Music effects                 616 non-null    object
 32  Permissions                   616 non-null    object
dtypes: float64(7), object(26)
memory usage: 163.6+ KB

In [63]:
df_limpio.dtypes  #Muestra de qué tipo es cada data

Timestamp                        object
Age                             float64
Primary streaming service        object
Hours per day                   float64
While working                    object
Instrumentalist                  object
Composer                         object
Fav genre                        object
Exploratory                      object
Foreign languages                object
BPM                             float64
Frequency [Classical]            object
Frequency [Country]              object
Frequency [EDM]                  object
Frequency [Folk]                 object
Frequency [Gospel]               object
Frequency [Hip hop]              object
Frequency [Jazz]                 object
Frequency [K pop]                object
Frequency [Latin]                object
Frequency [Lofi]                 object
Frequency [Metal]                object
Frequency [Pop]                  object
Frequency [R&B]                  object
Frequency [Rap]                  object
Frequency [Rock]                 object
Frequency [Video game music]     object
Anxiety                         float64
Depression                      float64
Insomnia                        float64
OCD                             float64
Music effects                    object
Permissions                      object
dtype: object

In [73]:
df1 = df.shape

print((df1))

(736, 33)